### PR TITLE
Mendelmax python config corrected and tested on CRAMPS2-Prusa-i3 setup

### PR DESCRIPTION
**Pull request by the-snowwhite**
After first trying to make a prusa-i3 clone I found out the original seemed untested and needed to get fixed first to establish a stable working starting point for other machines.

I had to make changes to the bb_io overlay to get the config to run. 
(finaly, replaced it with a known working hand edited one)
most step/dir pins were swapped, so this was corrected to enable joint movement

### CODE REVIEW

**Comment by the-snowwhite** [comment]
I would like to add that 
First I clean linuxcnc.log with:

```
machinekit@prusa-i3:~$ sudo chmod 666 /var/log/linuxcnc.log
machinekit@prusa-i3:~$ sudo echo "" > /var/log/linuxcnc.log
machinekit@prusa-i3:~$ sudo chmod 644 /var/log/linuxcnc.log
```

then starti mklauncher pointed to the config folder
and then trying to launch the original config with Machineface 
I get an error message ending with:
see the log file for details (gives no name of which log file ?)
However linuxcnc.log is empty
I could only get debug messages by executing the run.py instead.
(until different more cryptic error messages appear)
and then launch successfully with mklauncher

**Comment by the-snowwhite** [comment]
Ok the config should now be fully running and working with joint motion and temperature inputs

**Comment by machinekoder** [comment]
The problem with the error log is that the linuxcnc application does not output logging and error information to stdout or stderr. In fact I do not know where the output is directed to.

**Comment by machinekoder** [comment]
And thanks for the PR. I was wondering why my MendelMax was not moving... Looks like I swapped the BeBoPr pins in somewhere when porting...

**Pull request merged**
